repositories:
  - owner: "stephenmkbrady"
    repo: "boo_bot"
    display_name: "Matrix chat agent"
    feature: false
    image: "/notfeature-placeholder.jpg"
  - owner: "microsoft"
    repo: "vscode"
    display_name: "Visual Studio Code"
    feature: true
    image: "/blog-placeholder.jpg"
  - owner: "rust-lang"
    repo: "rust"
    display_name: "Rust Programming Language"
    feature: false
    image: "/notfeature-placeholder.jpg"